services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://workhole-api:8080
    container_name: rwafi-workhole
    ports:
      - "3002:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - workholebackend_workhole-network

networks:
  workholebackend_workhole-network:
    external: true
